services:
  database:
    image: postgres:13-alpine
    command: "-c 'config_file=/etc/postgresql/postgresql.conf'"
    container_name: database
    restart: unless-stopped
    networks:
      - mw-network
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - "${DATABASE_HOST_DIRECTORY}:/var/lib/postgresql/data"
      - ./database/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./database/host:/host
    working_dir: /host

networks:
  mw-network:
    driver: bridge
    name: mw-network
